name: financial_manager_app
description: "An app to manage financial goals and user authentication."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  shared_preferences: ^2.1.0
  csv: ^6.0.0
  path_provider: ^2.0.15
  image_picker: ^0.8.5+3    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
